export enum Role {
  ADMIN = 'ADMIN',
  STAFF = 'STAFF',
  ACCOUNTANT = 'ACCOUNTANT',
  MANAGER = 'MANAGER',
  DEVOTEE = 'DEVOTEE'
}

export enum PaymentMode {
  CASH = 'CASH',
  UPI = 'UPI',
  CARD = 'CARD',
  BANK = 'BANK'
}

export enum ReceiptKind {
  NEW_SEVA = 'NEW_SEVA',
  SHASHWATA_SEVA = 'SHASHWATA_SEVA',
  KIND_DONATION = 'KIND_DONATION',
  HUNDI_COLLECTION = 'HUNDI_COLLECTION'
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE'
}

export enum AnnouncementCategory {
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  EVENT = 'EVENT',
  DARSHAN_TIMINGS = 'DARSHAN_TIMINGS',
  GURU_PARAMPARA = 'GURU_PARAMPARA'
}
